<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\EticaretMicroservice.Shared\EticaretMicroservice.Shared.csproj" />
    <ProjectReference Include="..\EticaretMicroservice.Services.Order.Domain\EticaretMicroservice.Services.Order.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.0.16" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.0.16" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
